qub-it/fenixedu-academic

src/main/java/org/fenixedu/academic/ui/spring/controller/teacher/AttendsSearchController.java

NDS-LST-17/UL-IGOT-742: Add institutional email column to students excel on teacher's perspective

NDS-LST-17/UL-IGOT-742: Add institutional email column to students excel on teacher's perspective

---

pom.xml

Relates with: #qubIT-Omnis-5730

Removes commons-httpclient dependency

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/ui/spring/controller/teacher/authorization/AuthorizationService.java

Relates with: #qubIT-Omnis-5833

Removes @Service annotation from AuthorizationService

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/Person.java

Relates with: #qubIT-Omnis-5848

Removes hostname from avatarUrl

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/ExecutionCourse.java
src/main/resources/resources/ApplicationResources_en.properties
src/main/resources/resources/ApplicationResources_pt.properties

Relates With: #qubIT-Fenix-5338

Add Better error messages for execution course deletes

---

src/main/dml/fenixedu-academic.dml
src/main/java/org/fenixedu/academic/domain/person/vaccine/VaccineAdministration.java
src/main/java/org/fenixedu/academic/domain/person/vaccine/VaccineType.java
src/test/java/org/fenixedu/academic/domain/person/vaccine/VaccineTest.java

Relates with: #qubIT-Fenix-5476

Add Administration Date to VaccineAdministration

---

RELEASE_NOTES
src/main/dml/fenixedu-academic.dml
src/main/java/org/fenixedu/academic/domain/person/vaccine/VaccineAdministration.java
src/test/java/org/fenixedu/academic/domain/person/vaccine/VaccineTest.java

Relates With: #qubIT-Fenix-5477

Improvement: Change VaccineAdministration dates to LocalDate

---

RELEASE_NOTES
src/main/dml/fenixedu-academic.dml
src/main/java/org/fenixedu/academic/domain/BibliographicReference.java
src/main/java/org/fenixedu/academic/domain/ExecutionCourse.java
src/main/java/org/fenixedu/academic/service/services/manager/MergeExecutionCourses.java
src/main/resources/resources/ApplicationResources_en.properties
src/main/resources/resources/ApplicationResources_pt.properties

Relates with: #qubIT-Fenix-1595
This commit adds I18Ns to certain labels, deprecates methods and removes the unused ExecutionCourse relationship, adds one relationship with CompetenceCourseInformation

Refactor: complete Bibliographic Reference

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/BibliographicReference.java
src/main/java/org/fenixedu/academic/domain/degreeStructure/BibliographicReferences.java
src/main/java/org/fenixedu/academic/domain/degreeStructure/CompetenceCourseInformation.java
src/test/java/org/fenixedu/academic/domain/BibliographicReferenceMigrationTest.java
src/test/java/org/fenixedu/academic/domain/StranglerFigSwitchBibliographicReferencesTest.java

Relates with: #qubIT-Fenix-1595

Refactor: add Strangler Fig Switch to Bibliographic References

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/CompetenceCourse.java
src/test/java/org/fenixedu/academic/domain/BibliographicReferenceMigrationTest.java

Relates with: #qubIT-Fenix-1595

Add Bibliography methods to CompetenceCourse

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/BibliographicReference.java
src/main/resources/resources/ApplicationResources_en.properties
src/main/resources/resources/ApplicationResources_pt.properties
src/test/java/org/fenixedu/academic/domain/BibliographicReferenceMigrationTest.java

Correction of the create method of the Bibliographic Reference

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/organizationalStructure/Unit.java

Relates With: #ISCTE-FENIXEDU-471

Make getParentUnitsPresentationName method public

---

RELEASE_NOTES
src/main/dml/fenixedu-academic.dml
src/main/java/org/fenixedu/academic/domain/dml/DynamicField.java
src/main/java/org/fenixedu/academic/domain/dml/DynamicFieldDescriptor.java
src/main/java/org/fenixedu/academic/domain/dml/DynamicFieldValueConverter.java

Refactor: move DynamicFields from Academic-Extensions

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/Enrolment.java
src/main/java/org/fenixedu/academic/domain/OptionalEnrolment.java
src/main/java/org/fenixedu/academic/domain/log/CreditsDismissalLog.java
src/main/java/org/fenixedu/academic/domain/log/CurriculumLineLog.java
src/main/java/org/fenixedu/academic/domain/log/DismissalLog.java
src/main/java/org/fenixedu/academic/domain/log/EnrolmentLog.java
src/main/java/org/fenixedu/academic/domain/log/OptionalDismissalLog.java
src/main/java/org/fenixedu/academic/domain/log/OptionalEnrolmentLog.java
src/main/java/org/fenixedu/academic/domain/studentCurriculum/CreditsDismissal.java
src/main/java/org/fenixedu/academic/domain/studentCurriculum/CurriculumLine.java
src/main/java/org/fenixedu/academic/domain/studentCurriculum/Dismissal.java
src/main/java/org/fenixedu/academic/domain/studentCurriculum/OptionalDismissal.java
src/main/resources/resources/DomainExceptionResources_en.properties
src/main/resources/resources/DomainExceptionResources_pt.properties

Relates With: #qubIT-Fenix-5876

Refactor: Swap relation with EnrolmentAction to EnrolmentActionType

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/Enrolment.java
src/main/java/org/fenixedu/academic/domain/log/EnrolmentActionType.java
src/main/resources/resources/EnumerationResources_en.properties
src/main/resources/resources/EnumerationResources_pt.properties
src/test/java/org/fenixedu/academic/domain/AttendsTest.java
src/test/java/org/fenixedu/academic/domain/EnrolmentTest.java

Relates With: #qubIT-Fenix-5876

Add annullment and activation enrolment action types

---

RELEASE_NOTES
src/main/dml/fenixedu-academic.dml

Add dynamic field domain relation to teacher

---

RELEASE_NOTES
src/test/java/org/fenixedu/academic/domain/EnrolmentTest.java

Relates With: #qubIT-Fenix-5876

Add unit tests for CurriculumLineLog creation and EnrolmentActionType setters and getters

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/degreeStructure/CompetenceCourseInformation.java

Bug fix: Correctly copy bibliography on new version of competenceCourse

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/person/personIdentifier/PersonIdentifier.java

Improvement: add static update and search on PersonIdentifier

---

RELEASE_NOTES
src/main/dml/fenixedu-academic.dml
src/main/java/org/fenixedu/academic/domain/BibliographicReference.java
src/test/java/org/fenixedu/academic/domain/BibliographicReferenceTest.java

Refactor: remove fields of BibliographicReference

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/ui/rest/PhotographController.java

Relates with: #qubIT-Fenix-6024

PhotographController now never returns 404

---

RELEASE_NOTES
src/main/dml/fenixedu-academic.dml
src/main/java/org/fenixedu/academic/domain/util/email/UnitBasedSender.java

Relates with: #qubIT-Omnis-8289

Brings back UnitBasedSender

---

RELEASE_NOTES
src/main/resources/META-INF/web-fragment.xml

Relates with: #qubIT-Omnis-8309

Remove error pages from web fragment

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/student/Registration.java

Issue: #qubIT-Fenix-6558
I wanted to leave this one for today's night build.

Refactor: Clean creation methods in Registration

---

src/main/java/org/fenixedu/academic/domain/student/Registration.java

This partially reverts commit 9fb8db0c1701d194bf32b28c85efe414e2400696.

Partially Reverts "Refactor: Clean creation methods in Registration (#99)"

---

RELEASE_NOTES
src/main/dml/fenixedu-academic.dml
src/main/java/org/fenixedu/academic/domain/DegreeCurricularPlan.java
src/main/java/org/fenixedu/academic/dto/InfoDegreeCurricularPlan.java

Relates With: #qubIT-Fenix-6588

Refactor: Remove legacy class variables from DegreeCurricularPlan

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/accessControl/PersistentTeachersWithGradesToSubmitGroup.java

Relates with: #qubIT-Omnis-8526

Brings back necessary Group

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/util/email/PersonSender.java

Relates with: #qubIT-Omnis-7779

Replace references to soon to be discontinued PersonSender

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/degreeStructure/CompetenceCourseInformation.java

Relates With: #ISCTE-FENIXEDU-1034

Bug fix: Delete associated bibliographic references when deleting a competence course information

---

RELEASE_NOTES
src/main/dml/fenixedu-academic.dml
src/main/java/org/fenixedu/academic/domain/candidacy/StudentCandidacy.java
src/main/java/org/fenixedu/academic/domain/student/PrecedentDegreeInformation.java
src/main/java/org/fenixedu/academic/domain/student/Registration.java

Refactor: move PrecedentDegreeInformation to Registration

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/candidacy/StudentCandidacy.java

Refactor: remove PDIs initializer from StudentCandidacy

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/student/curriculum/calculator/ConclusionGradeCalculatorResultsDTO.java

Improvement: add description field to CalculatorDTO

---

RELEASE_NOTES
src/main/dml/fenixedu-academic.dml
src/main/java/org/fenixedu/academic/domain/student/curriculum/ConclusionProcessVersion.java
src/main/java/org/fenixedu/academic/dto/student/RegistrationConclusionBean.java

Add Conclusion Grade Calculator description to ConclusionProcessVersion

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/student/curriculum/ICurriculumEntry.java
src/main/resources/resources/ApplicationResources_en.properties
src/main/resources/resources/ApplicationResources_pt.properties

Refactor: add get type description to ICurriculumEntry

---

RELEASE_NOTES
src/main/dml/fenixedu-academic.dml
src/main/java/org/fenixedu/academic/domain/candidacy/StudentCandidacy.java

Refactor: remove numbers fields from StudentCandidacy

---

RELEASE_NOTES
src/main/dml/fenixedu-academic.dml
src/main/java/org/fenixedu/academic/domain/raides/DegreeClassification.java
src/main/java/org/fenixedu/academic/domain/student/personaldata/EducationLevelType.java
src/main/java/org/fenixedu/academic/domain/student/personaldata/ProfessionCategoryType.java
src/main/java/org/fenixedu/academic/domain/student/personaldata/ProfessionalStatusType.java
src/main/java/org/fenixedu/academic/servlet/FenixInitializer.java
src/main/resources/resources/ApplicationResources_en.properties
src/main/resources/resources/ApplicationResources_pt.properties

Relates with: #qubIT-Fenix-7009

Refactors SchoolLevelType, ProfessionType and ProfessionalSituationConditionType enums to domain entities

---

RELEASE_NOTES
src/main/dml/fenixedu-academic.dml
src/main/java/org/fenixedu/academic/domain/curricularRules/AnyCurricularCourse.java
src/main/java/org/fenixedu/academic/domain/curricularRules/executors/ruleExecutors/AnyCurricularCourseExecutor.java
src/main/resources/resources/BolonhaManagerResources_en.properties
src/main/resources/resources/BolonhaManagerResources_pt.properties

Improvement: Add DegreeCurricularPlan and Groups to AnyCurricularCourse

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/candidacy/StudentCandidacy.java
src/main/java/org/fenixedu/academic/domain/student/Registration.java
src/main/java/org/fenixedu/academic/dto/candidacy/IngressionInformationBean.java

Refactor: add proxy method PlacingOption to Regis.

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/CompetenceCourse.java
src/main/resources/resources/ApplicationResources_en.properties
src/main/resources/resources/ApplicationResources_pt.properties

Relates with: #qubIT-Fenix-6445

Add error labels for competence course deletion

---

src/main/java/org/fenixedu/academic/servlet/FenixInitializer.java

Relates with: #qubIT-Fenix-7009

Migrates data from enums to new entities

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/degreeStructure/CompetenceCourseInformation.java

Relates With: #qubIT-Fenix-6448

Refactor: Join hardcoded and dynamicField setters/getters for CompetenceCourseInformation refactor

---

RELEASE_NOTES
src/main/dml/fenixedu-academic.dml

Relates with: #qubIT-Fenix-7009
Must be released after: https://bitbucket.org/qub-it/qubedu.module.administrative-office/pull-requests/136

Deletes unused booleans from EducationLevelType

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/student/Registration.java
src/main/java/org/fenixedu/academic/servlet/FenixInitializer.java

without Student Candidacy as parameter
This commits is the first of many to further remove the remaining writes of StudentCandidacy
Issue: #qubIT-Fenix-6559

Refactor: add constructors to Registration

---

RELEASE_NOTES
src/main/java/org/fenixedu/academic/domain/accessControl/CandidateGroup.java

Issue: #qubIT-Fenix-6559
:warning: Can only be merged after our profile migration has ran

Refactor: deprecate CandidateGroup

---

RELEASE_NOTES
src/test/java/org/fenixedu/academic/domain/ExecutionIntervalTest.java
src/test/java/org/fenixedu/academic/domain/degreeStructure/CompetenceCourseInformationTest.java

Improvement: add year to ExecutionIntervalTest
